AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template to create a Security Group and an EC2 Instance
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP access
      VpcId: vpc-064f536de9612a5d8
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  PublicInstance4:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-03acbba64aef9bf5c
      KeyName: thuzar-aws-master-account
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup