AWSTemplateFormatVersion: '2010-09-09'

Description:
  'Private Subnet in ap-southeast-1 default VPC'
Resources:
  PrivateSubnet1: #PrivateSubnet1
    Type: AWS::EC2::Subnet
    Properties:
       #AssignIpv6AddressOnCreation: Boolean
      AvailabilityZone: 'ap-southeast-1a'
      #AvailabilityZoneId: String
      CidrBlock: '172.31.48.0/20'
      #EnableDns64: Boolean
      #EnableLniAtDeviceIndex: Integer
      #Ipv4IpamPoolId: String
      #Ipv4NetmaskLength: Integer
      #Ipv6CidrBlock: String
      #Ipv6IpamPoolId: String
      #Ipv6Native: Boolean
      #Ipv6NetmaskLength: Integer
      MapPublicIpOnLaunch: false
      #OutpostArn: String
      #PrivateDnsNameOptionsOnLaunch: 
        
      Tags: 
        - Key: Name
          Value: PrivateSubnet1
        - Key: Region
          Value: Singapore
        - Key : Environment
          Value: Non-production
      VpcId: 'vpc-064f536de9612a5d8'
  RouteTableForPrivateSubnet1: #routeTableForPrivateSubnet1
    Type: AWS::EC2::RouteTable
    Properties:
      Tags: 
      -   Key: Name
          Value: RouteTableForPrivateSubnet1
      -   Key: Region
          Value: Singapore
      -   Key : Environment
          Value: Non-production
      VpcId: vpc-064f536de9612a5d8
  PrivateSubnet1RouteTableAssociation: #PrivateSubnet1RouteTableAssociation
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTableForPrivateSubnet1
      SubnetId: !Ref PrivateSubnet1


  PrivateSubnet2: #PrivateSubnet2
    Type: AWS::EC2::Subnet
    Properties:
       #AssignIpv6AddressOnCreation: Boolean
      AvailabilityZone: 'ap-southeast-1b'
      #AvailabilityZoneId: String
      CidrBlock: '172.31.64.0/20'
      #EnableDns64: Boolean
      #EnableLniAtDeviceIndex: Integer
      #Ipv4IpamPoolId: String
      #Ipv4NetmaskLength: Integer
      #Ipv6CidrBlock: String
      #Ipv6IpamPoolId: String
      #Ipv6Native: Boolean
      #Ipv6NetmaskLength: Integer
      MapPublicIpOnLaunch: false
      #OutpostArn: String
      #PrivateDnsNameOptionsOnLaunch: 
        #PrivateDnsNameOptionsOnLaunch
      Tags: 
        - Key: Name
          Value: PrivateSubnet2
        - Key: Region
          Value: Singapore
        - Key : Environment
          Value: Non-production
      VpcId: vpc-064f536de9612a5d8
  RouteTableForPrivateSubnet2: #routeTableForPrivateSubnet2
    Type: AWS::EC2::RouteTable
    Properties:
      Tags: 
        - Key: Name
          Value: RouteTableForPrivateSubnet2
        - Key: Region
          Value: Singapore
        - Key : Environment
          Value: Non-production
      VpcId: vpc-064f536de9612a5d8
  PrivateSubnet2RouteTableAssociation: #PrivateSubnet2RouteTableAssociation
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTableForPrivateSubnet2
      SubnetId: !Ref PrivateSubnet2

  PrivateSubnet3: #PrivateSubnet3
    Type: AWS::EC2::Subnet
    Properties:
      #AssignIpv6AddressOnCreation: Boolean
      AvailabilityZone: 'ap-southeast-1c'
      #AvailabilityZoneId: String
      CidrBlock: '172.31.80.0/20'
      #EnableDns64: Boolean
      #EnableLniAtDeviceIndex: Integer
      #Ipv4IpamPoolId: String
      #Ipv4NetmaskLength: Integer
      #Ipv6CidrBlock: String
      #Ipv6IpamPoolId: String
      #Ipv6Native: Boolean
      #Ipv6NetmaskLength: Integer
      MapPublicIpOnLaunch: false
      #OutpostArn: String
      #PrivateDnsNameOptionsOnLaunch: 
        #PrivateDnsNameOptionsOnLaunch
      Tags: 
        - Key: Name
          Value: PrivateSubnet3
        - Key: Region
          Value: Singapore
        - Key : Environment
          Value: Non-production
      VpcId: 'vpc-064f536de9612a5d8'
  RouteTableForPrivateSubnet3: #routeTableForPrivateSubnet3
    Type: AWS::EC2::RouteTable
    Properties:
      Tags: 
        - Key: Name
          Value: RouteTableForPrivateSubnet3
        - Key: Region
          Value: Singapore
        - Key : Environment
          Value: Non-production
      VpcId: 'vpc-064f536de9612a5d8'
  PrivateSubnet3RouteTableAssociation: #logicalID
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTableForPrivateSubnet3
      SubnetId: !Ref PrivateSubnet3
  PrivateSubnet4: #PrivateSubnet4
    Type: AWS::EC2::Subnet
    Properties:
      
      AvailabilityZone: 'ap-southeast-1a'
      
      CidrBlock: '172.31.96.0/20'
      
      MapPublicIpOnLaunch: false
      
      Tags: 
        - Key: Name
          Value: PrivateSubnet4
        - Key: Region
          Value: Singapore
        - Key : Environment
          Value: Non-production
      VpcId: 'vpc-064f536de9612a5d8'
  RouteTableForPrivateSubnet4: #routeTableForPrivateSubnet4
    Type: AWS::EC2::RouteTable
    Properties:
      Tags: 
        - Key: Name
          Value: RouteTableForPrivateSubnet4
        - Key: Region
          Value: Singapore
        - Key : Environment
          Value: Non-production
      VpcId: 'vpc-064f536de9612a5d8'
  PrivateSubnet4RouteTableAssociation: #logicalID
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTableForPrivateSubnet4
      SubnetId: !Ref PrivateSubnet4
