AWSTemplateFormatVersion: '2010-09-09'
Resources:
  PublicInstance5:
    Type: AWS::EC2::Instance
    Properties:
        
        AvailabilityZone: 'ap-southeast-1a'
        ImageId: 'ami-0532913178263be11'
        InstanceType: 't2.micro'
        KeyName: 'thuzar'
        Tags:
          - Key: "Name"
            Value: "PublicInstance5"
          - Key: "Region"
            Value: "Singapore"
          - Key: "Environment"
            Value: "Non-Production"